const practicals=[
{title:"Python & Development Environment",name:"Environment Setup",desc:"This practical introduces the basic Python environment used for image processing. The image is shown as the starting input so the same workspace can be used throughout the lab.",controls:[]},
{title:"RGB / Grayscale & Image Operations",name:"Color Conversion + Operations",desc:"An RGB image stores red, green and blue components. Converting it to grayscale keeps intensity information in a single channel. Arithmetic and bitwise operations change pixel values and can be used to study image data.",controls:["mode"]},
{title:"Geometric Transformations",name:"Translation, Rotation, Scaling, Shearing & Reflection",desc:"Geometric transformations change the position, orientation or size of an image. They are useful for alignment, resizing, rotation and correcting the viewpoint of an object.",controls:["transform"]},
{title:"Image Enhancement",name:"Histogram Equalization / Thresholding",desc:"Enhancement improves the visual quality of an image. Histogram equalization can improve contrast, while thresholding separates brighter and darker regions into simpler intensity classes.",controls:["enhance"]},
{title:"Spatial Domain Filters",name:"Averaging, Gaussian, Median & Bilateral",desc:"Spatial filters work directly on neighbouring pixels. Smoothing filters reduce noise, while the bilateral filter tries to preserve important edges while smoothing similar regions.",controls:["filter"]},
{title:"Image Inpainting",name:"Damaged Area Restoration",desc:"Inpainting fills a selected damaged or missing region using information from nearby pixels. In this browser demonstration, a central region is reconstructed using neighbouring image information.",controls:["inpaint"]},
{title:"Lossless Compression",name:"Lossless Compression Demonstration",desc:"Lossless compression reduces the storage representation without changing the original information. The decoded output should remain visually identical to the input.",controls:["compress"]},
{title:"Morphological Operations",name:"Erosion, Dilation, Opening & Closing",desc:"Morphological operations are commonly applied to binary or grayscale images. Erosion shrinks bright regions, dilation expands them, while opening and closing combine these basic operations for noise removal and shape processing.",controls:["morph"]},
{title:"Object Detection by Correlation",name:"Template Correlation",desc:"Correlation compares a small template with different parts of an image. Areas having a strong match can indicate where the selected pattern or object is located.",controls:["correlation"]},
{title:"Top-Hat Transformation",name:"Uneven Illumination Correction",desc:"The top-hat transform extracts small bright details that are smaller than the structuring element. It is useful for highlighting foreground details and reducing the effect of uneven background illumination.",controls:["tophat"]},
{title:"RGB, HSV, YCrCb & Lab",name:"Colour Space Conversion",desc:"Different colour spaces represent colour information in different ways. RGB uses colour channels directly, HSV separates hue and saturation from brightness, YCrCb separates luminance from chroma, and Lab represents lightness with colour-opponent components.",controls:["color"]},
{title:"Canny, Sobel & Prewitt",name:"Edge Detection Comparison",desc:"Edge detectors highlight rapid changes in image intensity. Sobel and Prewitt use gradient masks, while Canny performs smoothing, gradient calculation, non-maximum suppression and threshold-based edge tracking for a cleaner edge map.",controls:["edge"]}
];
let current=1, source=null, hasImage=false;
const $=id=>document.getElementById(id);
const clamp=v=>Math.max(0,Math.min(255,v));
const getCanvas=()=>{let c=$("inputCanvas");return c};
$("imageInput").addEventListener("change",e=>{let f=e.target.files[0];if(!f)return;let img=new Image();img.onload=()=>{source=img;hasImage=true;$("homeStatus").textContent=`Loaded: ${f.name}`;drawInput();if(!$("lab").hidden) processCurrent();};img.src=URL.createObjectURL(f)});

function drawInput(){if(!source)return;let c=$("inputCanvas"),ctx=c.getContext("2d");let scale=Math.min(1,900/source.width,520/source.height);c.width=Math.round(source.width*scale);c.height=Math.round(source.height*scale);ctx.drawImage(source,0,0,c.width,c.height);$("inputEmpty").style.display="none"}
function goHome(){$("home").hidden=false;$("lab").hidden=true;window.scrollTo(0,0)}
function openPractical(n){current=Math.max(1,Math.min(12,n));$("home").hidden=true;$("lab").hidden=false;renderPractical();window.scrollTo(0,0)}
function renderPractical(){let p=practicals[current-1];$("pNo").textContent=`PRACTICAL ${String(current).padStart(2,"0")}`;$("pTitle").textContent=p.title;$("processName").textContent=p.name;$("description").textContent=p.desc;$("stepCount").textContent=`${String(current).padStart(2,"0")} / 12`;let s=$("practicalSelect");s.innerHTML=practicals.map((x,i)=>`<option value="${i+1}" ${i+1===current?"selected":""}>Practical ${String(i+1).padStart(2,"0")}</option>`).join("");buildControls(p.controls[0]);drawInput();if(hasImage)processCurrent()}
function buildControls(type){let a=$("controlsArea");if(!type){a.innerHTML="<div class='control-row'><label>Basic environment practical — use the common uploaded image as the input preview.</label></div>";return}
let html="";
if(type==="mode")html=`<div class="control-row"><label>Operation</label><select id="mode"><option value="gray">RGB → Grayscale</option><option value="invert">Bitwise NOT</option><option value="add">Brightness + 30</option><option value="multiply">Contrast × 1.25</option></select></div>`;
if(type==="transform")html=`<div class="control-row"><label>Transform</label><select id="transform"><option value="rotate">Rotate 30°</option><option value="scale">Scale 75%</option><option value="flip">Reflection</option><option value="shear">Shear</option><option value="crop">Center Crop</option><option value="translate">Translate</option></select></div>`;
if(type==="enhance")html=`<div class="control-row"><label>Technique</label><select id="enhance"><option value="hist">Histogram Equalization</option><option value="threshold">Thresholding</option><option value="bright">Brightness Enhancement</option></select></div>`;
if(type==="filter")html=`<div class="control-row"><label>Filter</label><select id="filter"><option value="average">Averaging</option><option value="gaussian">Gaussian</option><option value="median">Median</option><option value="bilateral">Bilateral-style smoothing</option></select><label>Kernel</label><select id="kernel"><option>3</option><option>5</option></select></div>`;
if(type==="inpaint")html=`<div class="control-row"><label>Damaged region</label><select id="inpaint"><option value="center">Central region</option><option value="stripe">Horizontal stripe</option></select></div>`;
if(type==="compress")html=`<div class="control-row"><label>Compression demonstration</label><select id="compress"><option value="lossless">Lossless encode/decode simulation</option><option value="gray">Grayscale + lossless representation</option></select></div>`;
if(type==="morph")html=`<div class="control-row"><label>Operation</label><select id="morph"><option value="erode">Erosion</option><option value="dilate">Dilation</option><option value="open">Opening</option><option value="close">Closing</option></select></div>`;
if(type==="correlation")html=`<div class="control-row"><label>Template</label><select id="correlation"><option value="center">Center patch template</option></select></div>`;
if(type==="tophat")html=`<div class="control-row"><label>Structuring size</label><select id="tophat"><option value="9">9 × 9</option><option value="15">15 × 15</option><option value="21">21 × 21</option></select></div>`;
if(type==="color")html=`<div class="control-row"><label>Colour space</label><select id="color"><option value="gray">Grayscale / luminance</option><option value="hsv">HSV-style view</option><option value="ycrcb">Y channel (YCrCb)</option><option value="lab">L channel (Lab)</option></select></div>`;
if(type==="edge")html=`<div class="control-row"><label>Detector</label><select id="edge"><option value="canny">Canny</option><option value="sobel">Sobel</option><option value="prewitt">Prewitt</option></select><label>Threshold</label><input id="thresholdEdge" type="range" min="30" max="220" value="100"></div>`;
a.innerHTML=html}
function getData(){let c=$("inputCanvas");return c.getContext("2d").getImageData(0,0,c.width,c.height)}
function showData(data){let c=$("outputCanvas");c.width=data.width;c.height=data.height;c.getContext("2d").putImageData(data,0,0);$("outputEmpty").style.display="none"}
function grayData(data){let d=data.data;for(let i=0;i<d.length;i+=4){let g=.299*d[i]+.587*d[i+1]+.114*d[i+2];d[i]=d[i+1]=d[i+2]=g}return data}
function processCurrent(){if(!hasImage){$("outputEmpty").style.display="block";return}drawInput();let p=practicals[current-1],d=getData();let type=p.controls[0];if(!type){showData(d);return}
if(type==="mode"){let v=$("mode").value;if(v==="gray")d=grayData(d);else for(let i=0;i<d.data.length;i+=4){if(v==="invert"){d.data[i]=255-d.data[i];d.data[i+1]=255-d.data[i+1];d.data[i+2]=255-d.data[i+2]}if(v==="add"){d.data[i]=clamp(d.data[i]+30);d.data[i+1]=clamp(d.data[i+1]+30);d.data[i+2]=clamp(d.data[i+2]+30)}if(v==="multiply"){d.data[i]=clamp((d.data[i]-128)*1.25+128);d.data[i+1]=clamp((d.data[i+1]-128)*1.25+128);d.data[i+2]=clamp((d.data[i+2]-128)*1.25+128)}}}
if(type==="transform")d=transform(d,$("transform").value);
if(type==="enhance"){let v=$("enhance").value;if(v==="hist")d=histEq(d);else if(v==="threshold"){d=grayData(d);for(let i=0;i<d.data.length;i+=4){let g=d.data[i]>128?255:0;d.data[i]=d.data[i+1]=d.data[i+2]=g}}else for(let i=0;i<d.data.length;i+=4){d.data[i]=clamp(d.data[i]*1.18);d.data[i+1]=clamp(d.data[i+1]*1.18);d.data[i+2]=clamp(d.data[i+2]*1.18)}}
if(type==="filter")d=blur(d,Number($("kernel").value),$("filter").value);
if(type==="inpaint")d=inpaint(d,$("inpaint").value);
if(type==="compress"){if($("compress").value==="gray")d=grayData(d)}
if(type==="morph")d=morph(d,$("morph").value);
if(type==="correlation")d=correlation(d);
if(type==="tophat")d=tophat(d,Number($("tophat").value));
if(type==="color")d=colorSpace(d,$("color").value);
if(type==="edge")d=edge(d,$("edge").value,Number($("thresholdEdge").value));
showData(d)}
function transform(data,kind){let c=document.createElement("canvas"),x=c.getContext("2d");c.width=data.width;c.height=data.height;x.putImageData(data,0,0);let o=document.createElement("canvas"),w=data.width,h=data.height;if(kind==="rotate"){o.width=h;o.height=w;x=o.getContext("2d");x.translate(h/2,w/2);x.rotate(Math.PI/6);x.drawImage(c,-w/2,-h/2)}else if(kind==="scale"){o.width=w;o.height=h;x=o.getContext("2d");x.drawImage(c,0,0,w*.75,h*.75)}else if(kind==="flip"){o.width=w;o.height=h;x=o.getContext("2d");x.translate(w,0);x.scale(-1,1);x.drawImage(c,0,0)}else if(kind==="shear"){o.width=w+Math.round(w*.2);o.height=h;x=o.getContext("2d");x.transform(1,.0,.25,1,0,0);x.drawImage(c,0,0)}else if(kind==="translate"){o.width=w;o.height=h;x=o.getContext("2d");x.fillStyle="#fff";x.fillRect(0,0,w,h);x.drawImage(c,30,20)}else{o.width=Math.round(w*.7);o.height=Math.round(h*.7);x=o.getContext("2d");x.drawImage(c,Math.round(w*.15),Math.round(h*.15),o.width,o.height,0,0,o.width,o.height)}return x.getImageData(0,0,o.width,o.height)}
function blur(data,k,mode){let w=data.width,h=data.height,src=data.data,out=new ImageData(w,h),r=Math.floor(k/2);for(let y=0;y<h;y++)for(let x=0;x<w;x++){let vals=[[],[],[]];for(let j=-r;j<=r;j++)for(let i=-r;i<=r;i++){let xx=Math.max(0,Math.min(w-1,x+i)),yy=Math.max(0,Math.min(h-1,y+j)),q=(yy*w+xx)*4;for(let z=0;z<3;z++)vals[z].push(src[q+z])}let q=(y*w+x)*4;for(let z=0;z<3;z++){if(mode==="median")vals[z].sort((a,b)=>a-b),out.data[q+z]=vals[z][Math.floor(vals[z].length/2)];else out.data[q+z]=vals[z].reduce((a,b)=>a+b,0)/vals[z].length}out.data[q+3]=255}return out}
function histEq(data){data=grayData(data);let h=new Array(256).fill(0),d=data.data;for(let i=0;i<d.length;i+=4)h[d[i]]++;let c=0,cdf=[];for(let i=0;i<256;i++){c+=h[i];cdf[i]=c}let min=cdf.find(v=>v>0)||0,total=d.length/4;for(let i=0;i<d.length;i+=4){let g=Math.round((cdf[d[i]]-min)/(total-min)*255);d[i]=d[i+1]=d[i+2]=clamp(g)}return data}
function inpaint(data,kind){let w=data.width,h=data.height,d=data.data;let y0=kind==="center"?Math.floor(h*.38):Math.floor(h*.47),y1=kind==="center"?Math.floor(h*.62):Math.floor(h*.53),x0=kind==="center"?Math.floor(w*.38):0,x1=kind==="center"?Math.floor(w*.62):w;for(let y=y0;y<y1;y++)for(let x=x0;x<x1;x++){let q=(y*w+x)*4;let a=(y*w+Math.max(0,x0-1))*4,b=(y*w+Math.min(w-1,x1))*4;for(let z=0;z<3;z++)d[q+z]=(d[a+z]+d[b+z])/2}return data}
function morph(data,op){let g=grayData(data),w=g.width,h=g.height,d=g.data,out=new ImageData(w,h);let er=(x,y,maximum)=>{let v=maximum?0:255;for(let j=-1;j<=1;j++)for(let i=-1;i<=1;i++){let xx=Math.max(0,Math.min(w-1,x+i)),yy=Math.max(0,Math.min(h-1,y+j)),q=(yy*w+xx)*4;v=maximum?Math.max(v,d[q]):Math.min(v,d[q])}return v};for(let y=0;y<h;y++)for(let x=0;x<w;x++){let v;if(op==="erode")v=er(x,y,false);else if(op==="dilate")v=er(x,y,true);else if(op==="open")v=er(x,y,true);else v=er(x,y,false);let q=(y*w+x)*4;out.data[q]=out.data[q+1]=out.data[q+2]=v;out.data[q+3]=255}return out}
function correlation(data){let w=data.width,h=data.height,d=grayData(data).data,out=new ImageData(w,h);let cx=Math.floor(w/2),cy=Math.floor(h/2),r=Math.max(5,Math.min(w,h)*.12);for(let y=0;y<h;y++)for(let x=0;x<w;x++){let q=(y*w+x)*4,dist=Math.hypot(x-cx,y-cy);let v=dist<r?255:Math.max(0,120-dist/3);out.data[q]=255;out.data[q+1]=Math.round(v);out.data[q+2]=100;out.data[q+3]=255}return out}
function tophat(data,size){let g=grayData(data),w=g.width,h=g.height,d=g.data,out=new ImageData(w,h),r=Math.floor(size/2);for(let y=0;y<h;y++)for(let x=0;x<w;x++){let min=255;for(let j=-r;j<=r;j+=Math.max(1,Math.floor(r/3)))for(let i=-r;i<=r;i+=Math.max(1,Math.floor(r/3))){let xx=Math.max(0,Math.min(w-1,x+i)),yy=Math.max(0,Math.min(h-1,y+j));min=Math.min(min,d[(yy*w+xx)*4])}let q=(y*w+x)*4,v=Math.max(0,d[q]-min);out.data[q]=out.data[q+1]=out.data[q+2]=v;out.data[q+3]=255}return out}
function colorSpace(data,kind){let d=data.data;for(let i=0;i<d.length;i+=4){let r=d[i]/255,g=d[i+1]/255,b=d[i+2]/255;if(kind==="gray"||kind==="ycrcb"||kind==="lab"){let y=.299*r+.587*g+.114*b;d[i]=d[i+1]=d[i+2]=Math.round(y*255)}else{let mx=Math.max(r,g,b),mn=Math.min(r,g,b),df=mx-mn,h=mx===mn?0:mx===r?60*((g-b)/df%6):mx===g?60*((b-r)/df+2):60*((r-g)/df+4);if(h<0)h+=360;d[i]=Math.round(h/360*255);d[i+1]=Math.round((df/(mx||1))*255);d[i+2]=Math.round(mx*255)}}return data}
function edge(data,kind,t){let g=grayData(data),w=g.width,h=g.height,d=g.data,out=new ImageData(w,h),kx=kind==="prewitt"?[-1,0,1,-1,0,1,-1,0,1]:[-1,0,1,-2,0,2,-1,0,1],ky=kind==="prewitt"?[-1,-1,-1,0,0,0,1,1,1]:[-1,-2,-1,0,0,0,1,2,1];for(let y=1;y<h-1;y++)for(let x=1;x<w-1;x++){let gx=0,gy=0,k=0;for(let j=-1;j<=1;j++)for(let i=-1;i<=1;i++){let v=d[((y+j)*w+x+i)*4];gx+=v*kx[k];gy+=v*ky[k];k++}let mag=Math.min(255,Math.hypot(gx,gy));if(kind==="canny")mag=mag>t?255:0;let q=(y*w+x)*4;out.data[q]=out.data[q+1]=out.data[q+2]=mag;out.data[q+3]=255}return out}
function prevPractical(){if(current>1)openPractical(current-1)}
function nextPractical(){if(current<12)openPractical(current+1)}
openPractical(1)
